apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.sample.io
spec:
  group: samplecontroller.sample.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
  scope: Namespaced