apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.sample.io
spec:
  group: samplecontroller.sample.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                fieldA:
                  type: string
                fieldB:
                  type: string
                fieldC:
                  type: string
  names:
    kind: Foo
    plural: foos
  scope: Namespaced